[modules]
left = [["CPU", "RAM", "GPU"]]
center = ["Workspaces"]
right = [["Tray", "KeyboardLayout", "Settings", "Clock", "Privacy"]]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = true

[keyboard_layout.labels]
"English (US)" = "EN"
"Russian" = "RU"

[clock]
format = "%T"

[[CustomModule]]
name = "GPU"
command = ""
icon = "󰢮"
listen_cmd = "bash ~/.config/ashell/scripts/gpu.sh"

[[CustomModule]]
name = "CPU"
command = ""
icon = ""
listen_cmd = "bash ~/.config/ashell/scripts/cpu.sh"

[[CustomModule]]
name = "RAM"
command = ""
icon = ""
listen_cmd = "bash ~/.config/ashell/scripts/ram.sh"

[[CustomModule]]
name = "Netspeed"
command = " "
icon = ""
listen_cmd = "bash ~/.config/ashell/scripts/netspeed.sh"

[appearance]
font_name = "JetBrainsMono Nerd Font"
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = ["#7aa2f7", "#9ece6a"]
scale_factor = 1

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
